### ISSUE TITLE
All symbol links in node_modules/.bin are broken after npm-cache install extract the archive

### ISSUE THREAD

**Issue by hax** [swarajban/npm-cache#33]
I checked the archive and it's ok, and v0.4.10 do not have this bug. So the problem is due to using Decompress package. I suggest to switch back to targz or just call tar cli.

**Comment by hax** [comment]
And I have tested the packages which provide tar functionality such as tar-fs, node-tar ... , and found that all those packages are much slower than tar cli. 

My cached npm archive is about 29MB (600+ packages), which tar-fs need 30s to decompress, node-tar need 1m+ to decompress, and tar cli only use 2.5s. (Test on a CentOS 6 machine)

So I suggest to just call tar cli.

**Comment by swarajban** [comment]
Thanks for investigating. The reason I am using the other tar packages is because they have windows support. The `tar` CLI on *nix machines is faster, but doesn't work on windows. 

I didn't realize that the CLI was so much faster, so it would be nice to have an option to let you use the CLI if you wanted. 

Unfortunately, I don't have much spare time these days to work on this, but happy to review & merge in any PRs.

**Comment by hax** [comment]
I will submit a PR if I have time next week.

This is my plan:
0. Write a new wrapper package for tar cli (I checked npmjs.org and found only one similar package `ext-tar` but its code seems unnecessary complex so I decide to write one by myself.)
0. `ext-tar` ship a `TarTool.exe` and dependant DLL for Windows, it works but I think we could also just use zip in Windows. Because `npm-cache` just need archive/unarchive , and should not care about archive format.
0. Update `npm-cache` to use my wrapper package replace `Decompress` or `targz` package.


Is this plan ok?

**Comment by swarajban** [comment]
That would certainly work, I would like to always use `tar` if possible because some users have already started using this on Windows, and we'll break their flows if we switch to `zip`.

I would recommend enabling the a CLI version of `tar` with a flag like,` --useCliTar` so people can enable it if they want. I still like the `tar.gz` and `decompress` packages because they work the same cross-platform.

What do you think?

**Comment by swarajban** [comment]
@hax Please check out the latest version of `npm-cache`, 0.5.2. Someone just submitted a PR that uses a different tar dependency that should fix this issue.
