### ISSUE TITLE
Add ability to store cached packages at server

### ISSUE THREAD

**Issue by stasberkov** [swarajban/npm-cache#61]
It would be really great if npm-cache could cache packages not only locally but at some server. Then we could use it as corporate package proxy server.

**Comment by darthsteven** [comment]
I'm not hugely experienced with nodejs stuff, but from my understanding this would be incredibly hard to do because a lot of npm modules contain C code that gets compiled on package install.

Presumably npm-cache lets the build run, and then archives that.

Thus, packages would be cached in such a way as to built for specific machines and the specific libraries on them that the C code links to etc.

So, you'd have to ensure that all your systems were identical for this strategy to work.

If you're just after caching the downloads of node modules, then there npm registry caches that can provide such a tool.

**Comment by swarajban** [comment]
@darthsteven that's correct. I just cache packages built wherever npm ran. If you could be certain that the consumers of the cached packages could use cached packages remotely

**Comment by swarajban** [comment]
Closing this as I don't plan on adding this in the near future. Happy to accept a PR though
