### ISSUE TITLE
Why does it clear installed dependencies if nothing changed?

### ISSUE THREAD

**Issue by IAMtheIAM** [swarajban/npm-cache#65]
This seemed like a great idea. It uses cache instead of a million http requests. Thats great. But why does it clear all my existing node_modules and bower_components every time I run "npm-cache install"? 

I thought the point is to reduce the amount of time npm install takes. Now it just deletes the dependencies and reinstalls the exact same ones. 

Can you make it check if installed dependencies matches the hashtag for cached dependencies, and if so, stop execution? That would make it really speedy.

**Comment by swarajban** [comment]
What you're requesting would require each dependency manager to be able to quickly determine if what was in `node_modules` matched package.json. That is not possible in all package managers, so npm-cache simply wipes the dependency directory, and untars the cached files.

npm-cache is best suited for CI pipelines that run `npm | bower | jspm | composer install` after checking out a git repo where none of the dependencies have been installed yet.

When working locally, often just doing `npm install` will work best because npm is smart enough to look inside node_modules, and figure out what it needs to change.

Open to other suggestions, but I don't think I'll be adding this feature soon.
